version: '3.8'
services:
  dev-db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: con-cruise
    networks:
      - devNetwork


networks:
  devNetwork:


